version: '26.1.1'

networks:
  dev:
    driver: bridge

services:
   demoapp:
     container_name: demoapp
     image: docker.io/library/demoapp 
     build: .
     ports:
      - "8080:80"
     environment:
       ConnectionStrings__myConnections: "Host=app_db;Database=StudentDb;Username=postgres;Password=postgres"
     depends_on:
       - app_db  
     networks:
       - dev  
   app_db:
    container_name: app_db
    image: postgres:latest
    ports:
      - "5432:5432"

    restart: always  

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: StudentDb


    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev  

volumes:
  app_data: {}    
      
#docker.io/library/demoapp        


